# 使用单次卷积加全连接层的方法分类

In [1]:
from keras import Sequential
from keras import utils
from keras import layers
from keras import models
from keras import optimizers
from keras import preprocessing

import numpy as np
import os
import sys

Using TensorFlow backend.


In [2]:
os.chdir('/Users/james/MobileProximateSpeech/Analysis/')

In [5]:
from utils.voice_data_loader import load_ftr_from_dir, train_test_split, DataPack, show_shape

In [70]:
ftr_files, file_labels, file_names = load_ftr_from_dir('Data/Sounds/yzc/')
len(ftr_files)

loading from Data/Sounds/yzc/...
shuffled.
loaded.


72

In [78]:
data = np.array([i for i in range(21)])
targets = np.array([i for i in range(21)])

data_gen = preprocessing.sequence.TimeseriesGenerator(data, targets, sampling_rate=1, length=4, stride=2, batch_size=3)
print(len(data_gen))
for x, y in data_gen:
    print(x)
    print(y)
    print()

3
[[0. 1. 2. 3.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]]
[4. 6. 8.]

[[ 6.  7.  8.  9.]
 [ 8.  9. 10. 11.]
 [10. 11. 12. 13.]]
[10. 12. 14.]

[[12. 13. 14. 15.]
 [14. 15. 16. 17.]
 [16. 17. 18. 19.]]
[16. 18. 20.]



In [74]:
show_shape(ftr_files[0])

(40, 966)


In [102]:
X_batches, y_batches = [], []
for ftr_file, label in zip(ftr_files, file_labels):
    ftr_file = np.rollaxis(ftr_file, 1, 0) # time dim first
    data_gen = preprocessing.sequence.TimeseriesGenerator(
        ftr_file, np.array([label for _ in ftr_file]), 
        start_index=50, end_index=len(ftr_file) - 50,
        length=10, stride=5, batch_size=5)
    for X_batch, y_batch in data_gen:
        X_batches.append(X_batch)
        y_batches.append(y_batch)
show_shape(X_batches)
show_shape(y_batches)

(2603,)
(2603,)
